version: '3'
services:
  #--- Jupyter Notebook ---
  notebook:
    build:
      context: .
      dockerfile: ./jupyter-notebook-docker/Dockerfile
    ports:
      - "8888:8888"
    depends_on: 
      - mlflow
    environment: 
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    # volumes: 
    #   - //c/:/home/jovyan
  #--- ML Flow Server ---
  mlflow:
    build:
      context: ./ml-flow-docker
    expose: 
      - "5000"
    ports:
      - "5000:5000"
    depends_on: 
      - postgres
  #--- Postgres DB ---
  postgres:
    #image: postgres:alpine
    build:
      context: ./postgres-docker
    restart: always
    environment:
        POSTGRES_PASSWORD: 'admin'
    ports: 
      - "5433:5432"